language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install nose
  - pip install coverage
script:
  - python setup.py install
  - nosetests --with-coverage # Add me to run nose with coverage support.
after_success: 
    -coveralls
