language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coveralls
  - pip install nose
  - pip install coverage

script:
  #- python setup.py install
  #- nosetests --with-coverage 
  - pytest 

after_success: 
  - coveralls
